# ent-core .travis.yml

language: java

cache:
    directories:
        - $HOME/.m2

before_install:
    - chmod +x gradlew

jdk:
    - openjdk8

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always
